### ISSUE TITLE
Hass is not a function

### ISSUE THREAD

**Issue by Vincentkerstholt** [filp/homeassistant-ws#2]
If i just try to run your package with the following code, as per the readme;

```javascript
import hass from 'homeassistant-ws'

async function main () {
	const client =  await hass({
		protocol: 'ws',
		host: 'My-IP',
		port: 8123,
		path: '/api/websocket',
		// Must be set if HA expects authentication:
		token: 'my-token'
	})
}

main()
  .then(console.log)
  .catch(console.error)
```

I get the error message that hass is not a function.

**Comment by Vincentkerstholt** [comment]
Already saw in the code, that on line https://github.com/filp/homeassistant-ws/blob/c7223f708cbd19ea54a014fbfcb358f163d7d495/src/index.js#L162  createClient is exported as a default function.

**Comment by Vincentkerstholt** [comment]
Got it working, by rewriting the creating a module.exports from the createClient function

```javascript
module.exports = async function createClient(callerOptions = {}) {
```

**Comment by Vincentkerstholt** [comment]
By knowing that the default export didin't go correct, i reverted my change above and called the hass function like:

```javascript
const client = await hass.default({
```

Now the code is working.

**Comment by Timmiej93** [comment]
Why is this issue closed? Vincent's workaround works, but the issue isn't fixed. Also, the example on the main page still shows this snippet below, which throws the error.

```js
import hass from 'homeassistant-ws';

async function main() {
  const client = await hass({
  ...
```
